/*=============================================================
  Snow편의점 ML Workshop - DDL
  Database: SNOW_ML_WORKSHOP / Schema: CVS_DEMO
=============================================================*/

USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS SNOW_ML_WORKSHOP;
CREATE SCHEMA IF NOT EXISTS SNOW_ML_WORKSHOP.CVS_DEMO;

USE DATABASE SNOW_ML_WORKSHOP;
USE SCHEMA CVS_DEMO;

-- 1. 매장 마스터
CREATE OR REPLACE TABLE STORES (
    STORE_ID       VARCHAR(20)  NOT NULL,
    STORE_NAME     VARCHAR(100),
    REGION         VARCHAR(50),
    STORE_TYPE     VARCHAR(20),
    OPEN_DATE      DATE
);

-- 2. 상품 마스터
CREATE OR REPLACE TABLE PRODUCTS (
    PRODUCT_ID     VARCHAR(20)  NOT NULL,
    PRODUCT_NAME   VARCHAR(200),
    CATEGORY_L1    VARCHAR(50),
    CATEGORY_L2    VARCHAR(50),
    UNIT_PRICE     NUMBER(18,2),
    UNIT_COST      NUMBER(18,2),
    IS_SEASONAL    BOOLEAN
);

-- 3. 시간별 매출 트랜잭션
CREATE OR REPLACE TABLE HOURLY_SALES (
    SALE_ID        VARCHAR(50)  NOT NULL,
    SALE_DATETIME  TIMESTAMP_NTZ,
    SALE_DATE      DATE,
    HOUR_OF_DAY    NUMBER(38,0),
    TIME_SLOT      VARCHAR(20),
    STORE_ID       VARCHAR(20),
    PRODUCT_ID     VARCHAR(20),
    CATEGORY_L1    VARCHAR(50),
    CATEGORY_L2    VARCHAR(50),
    QUANTITY       NUMBER(38,0),
    UNIT_PRICE     NUMBER(18,2),
    SALES_AMOUNT   NUMBER(18,2),
    REGION         VARCHAR(50)
);

-- 4. 날씨 데이터
CREATE OR REPLACE TABLE WEATHER_DATA (
    WEATHER_DATE      DATE        NOT NULL,
    REGION            VARCHAR(50) NOT NULL,
    TEMPERATURE       NUMBER(5,1),
    WEATHER_CONDITION VARCHAR(50),
    HUMIDITY          NUMBER(5,1),
    PRECIPITATION     NUMBER(5,1)
);

-- 5. 한국 이벤트/공휴일
CREATE OR REPLACE TABLE KOREAN_EVENTS (
    EVENT_DATE            DATE        NOT NULL,
    EVENT_NAME            VARCHAR(100),
    EVENT_TYPE            VARCHAR(50),
    IMPACT_CATEGORIES     VARCHAR(500),
    EXPECTED_SALES_IMPACT VARCHAR(100)
);

-- 예측 결과 저장 테이블
CREATE OR REPLACE TABLE SALES_FORECAST (
    FORECAST_DATE   DATE,
    REGION          VARCHAR(50),
    CATEGORY_L1     VARCHAR(50),
    PREDICTED_SALES NUMBER(18,2),
    LOWER_BOUND     NUMBER(18,2),
    UPPER_BOUND     NUMBER(18,2),
    MODEL_VERSION   VARCHAR(50),
    CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 모델 메타데이터 테이블
CREATE OR REPLACE TABLE ML_MODEL_REGISTRY (
    MODEL_NAME          VARCHAR(100),
    MODEL_VERSION       VARCHAR(20),
    MODEL_TYPE          VARCHAR(50),
    INPUT_TABLE         VARCHAR(200),
    TARGET_COLUMN       VARCHAR(50),
    TRAINING_START_DATE DATE,
    TRAINING_END_DATE   DATE,
    TRAINING_ROWS       NUMBER,
    FORECAST_HORIZON    NUMBER,
    STATUS              VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY          VARCHAR(100) DEFAULT CURRENT_USER()
);

-- 모니터링 로그 테이블
CREATE OR REPLACE TABLE ML_MONITORING_LOG (
    LOG_ID          NUMBER AUTOINCREMENT,
    MODEL_NAME      VARCHAR(100),
    MODEL_VERSION   VARCHAR(20),
    EVAL_DATE       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    METRIC_NAME     VARCHAR(50),
    METRIC_VALUE    FLOAT,
    THRESHOLD_VALUE FLOAT,
    IS_ALERT        BOOLEAN,
    NOTES           VARCHAR(500)
);

SELECT '✅ DDL 완료 - SNOW_ML_WORKSHOP.CVS_DEMO 테이블 8개 생성' AS STATUS;
