/*=============================================================
  Snow편의점 ML Workshop - Task 스케줄링
  주 1회 자동 재학습 + 예측 + 모니터링
=============================================================*/

USE DATABASE SNOW_ML_WORKSHOP;
USE SCHEMA CVS_DEMO;

CREATE OR REPLACE WAREHOUSE ML_WORKSHOP_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

-- Task 1: 주 1회 모델 재학습 (매주 월요일 02:00 KST)
CREATE OR REPLACE TASK RETRAIN_FORECAST_MODELS
    WAREHOUSE = ML_WORKSHOP_WH
    SCHEDULE = 'USING CRON 0 2 * * 1 Asia/Seoul'
AS
BEGIN
    -- 전체 매출 모델 재학습
    CREATE OR REPLACE SNOWFLAKE.ML.FORECAST SNOW_ML_WORKSHOP.CVS_DEMO.TOTAL_SALES_FORECAST(
        INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'SNOW_ML_WORKSHOP.CVS_DEMO.TS_DAILY_TOTAL'),
        TIMESTAMP_COLNAME => 'DS',
        TARGET_COLNAME => 'Y'
    );
    -- 카테고리별 모델 재학습
    CREATE OR REPLACE SNOWFLAKE.ML.FORECAST SNOW_ML_WORKSHOP.CVS_DEMO.CATEGORY_SALES_FORECAST(
        INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'SNOW_ML_WORKSHOP.CVS_DEMO.TS_CATEGORY_DAILY'),
        SERIES_COLNAME => 'SERIES',
        TIMESTAMP_COLNAME => 'DS',
        TARGET_COLNAME => 'Y'
    );
END;

-- Task 2: 재학습 후 예측 결과 갱신
CREATE OR REPLACE TASK UPDATE_FORECAST_RESULTS
    WAREHOUSE = ML_WORKSHOP_WH
    AFTER RETRAIN_FORECAST_MODELS
AS
BEGIN
    TRUNCATE TABLE SNOW_ML_WORKSHOP.CVS_DEMO.SALES_FORECAST;
    
    INSERT INTO SNOW_ML_WORKSHOP.CVS_DEMO.SALES_FORECAST 
        (FORECAST_DATE, REGION, CATEGORY_L1, PREDICTED_SALES, LOWER_BOUND, UPPER_BOUND, MODEL_VERSION)
    SELECT TS, '전체', '전체', FORECAST, LOWER_BOUND, UPPER_BOUND, 'total_v1'
    FROM TABLE(SNOW_ML_WORKSHOP.CVS_DEMO.TOTAL_SALES_FORECAST!FORECAST(FORECASTING_PERIODS => 30));

    INSERT INTO SNOW_ML_WORKSHOP.CVS_DEMO.SALES_FORECAST 
        (FORECAST_DATE, REGION, CATEGORY_L1, PREDICTED_SALES, LOWER_BOUND, UPPER_BOUND, MODEL_VERSION)
    SELECT TS, '전체', SERIES, FORECAST, LOWER_BOUND, UPPER_BOUND, 'category_v1'
    FROM TABLE(SNOW_ML_WORKSHOP.CVS_DEMO.CATEGORY_SALES_FORECAST!FORECAST(FORECASTING_PERIODS => 30));
END;

-- Task 3: 모니터링 로그 기록
CREATE OR REPLACE TASK LOG_MODEL_PERFORMANCE
    WAREHOUSE = ML_WORKSHOP_WH
    AFTER UPDATE_FORECAST_RESULTS
AS
BEGIN
    INSERT INTO SNOW_ML_WORKSHOP.CVS_DEMO.ML_MONITORING_LOG 
        (MODEL_NAME, MODEL_VERSION, METRIC_NAME, METRIC_VALUE, THRESHOLD_VALUE, IS_ALERT, NOTES)
    SELECT 
        'TOTAL_SALES_FORECAST',
        'v1.0',
        'MAPE',
        AVG(APE_PCT),
        20.0,
        CASE WHEN AVG(APE_PCT) > 20.0 THEN TRUE ELSE FALSE END,
        CASE 
            WHEN AVG(APE_PCT) > 20.0 THEN '⚠️ MAPE 임계값 초과 - 모델 재학습 권장'
            WHEN AVG(APE_PCT) > 15.0 THEN '⚡ MAPE 주의 수준 - 모니터링 강화'
            ELSE '✅ 정상 범위 내 운영 중'
        END
    FROM (
        SELECT ABS(a.Y - COALESCE(p.PREDICTED_SALES, a.Y)) / a.Y * 100 AS APE_PCT
        FROM SNOW_ML_WORKSHOP.CVS_DEMO.TS_DAILY_TOTAL a
        LEFT JOIN SNOW_ML_WORKSHOP.CVS_DEMO.SALES_FORECAST p 
            ON a.DS = p.FORECAST_DATE AND p.CATEGORY_L1 = '전체'
        WHERE a.DS >= DATEADD(DAY, -30, (SELECT MAX(DS) FROM SNOW_ML_WORKSHOP.CVS_DEMO.TS_DAILY_TOTAL))
          AND p.PREDICTED_SALES IS NOT NULL
    );
END;

-- Task 활성화
ALTER TASK LOG_MODEL_PERFORMANCE RESUME;
ALTER TASK UPDATE_FORECAST_RESULTS RESUME;
ALTER TASK RETRAIN_FORECAST_MODELS RESUME;

-- 확인
SHOW TASKS IN SCHEMA SNOW_ML_WORKSHOP.CVS_DEMO;

SELECT '✅ Task 스케줄링 완료 - 매주 월요일 02:00 (KST) 자동 실행' AS STATUS;
